version: "3.8"

services:
  discord-bot:
    build: .
    image: discord-bot:local
    container_name: discord-bot
    env_file:
      - .env
    volumes:
      - "./db.sqlite:/db.sqlite"
    restart: unless-stopped
